// netlify/functions/_utils/csrf.js
const cookie = require('cookie');

/**
 * Validates CSRF token by comparing the cookie value with the header value.
 * Both must be present and match exactly.
 * Expected token format: 64-character hex string (generated by crypto.getRandomValues).
 */
function validateCsrf(event) {
  const cookies = cookie.parse(event.headers.cookie || '');
  const csrfCookie = cookies.csrf_token;
  const csrfHeader = event.headers['x-csrf-token'];

  // Both must be present and non‑empty strings
  if (!csrfCookie || !csrfHeader || typeof csrfCookie !== 'string' || typeof csrfHeader !== 'string') {
    console.warn('CSRF validation failed: missing cookie or header');
    return false;
  }

  // Validate format: 64 hexadecimal characters
  const hexRegex = /^[a-f0-9]{64}$/;
  if (!hexRegex.test(csrfCookie) || !hexRegex.test(csrfHeader)) {
    console.warn('CSRF validation failed: invalid token format');
    return false;
  }

  if (csrfCookie !== csrfHeader) {
    console.warn('CSRF validation failed: cookie and header mismatch');
    return false;
  }

  // Success
  return true;
}

module.exports = { validateCsrf };